FROM node:latest as base

WORKDIR /usr/app

COPY package*.json .

RUN npm install


### DEV
FROM base as dev

RUN npm install -g nodemon
CMD nodemon src/index.js

### PROD
FROM base as prod

COPY src ./src

CMD npm run start
